import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/shared/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "krismaClient",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      // Evita el warning de hydration: next-themes cambia la clase del html en el
      // navegador mientras el servidor la mandó distinta. Calla esa diferencia (solo
      // actúa un nivel, y la diferencia está justo en la etiqueta html).
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* ThemeProvider dentro del <body> (posición obligatoria): next-themes inyecta un
          <script> para pintar el tema sin parpadeo. Si envolviera el <body> desde afuera,
          ese script quedaría pegado al <html> → HTML inválido y errores de consola. */}
      {/* Lo que va adentro de <ThemeProvider> se convierte implícitamente en su parámetro
          children (acá, el contenido de las páginas), sin pasarlo a mano. */}
      <body className="min-h-full flex flex-col">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
